"""
DO NOT EDIT THIS FILE.

This file is a grading criteria artifact that measures the training stability
of the Poker GPU environment. It tracks reward stability, TD error trends,
Q-value bounds, and gradient clipping rates to ensure our agent is learning 
steadily over time.
"""

import gymnasium as gym
import torch
import time
from pathlib import Path
from utils.torch import load_device
from environments.Poker.Player import PokerQNetwork
from environments.Poker.utils import PokerAgentType, build_actions, get_rotated_agents, load_gpu_agents
from utils.logging.logger import TrainingLogger
from utils.stability import (
    calculate_final_stability_metrics,
    run_stability_measured_q_learning_step,
    summarize_episode_stability_metrics,
)


STABILITY_BENCHMARK_DEFAULTS = {
    "NUM_PLAYERS": 9,
    "N_GAMES": 100000,
    "EPISODES": 50,
    "STARTING_BBS": 100,
    "POKER_ACTION_SPACE_N": 13,
    "STATE_SPACE": 40,
    "ACTION_SPACE": 13,
    "GAMMA": 0.95,
    "UPDATE_FREQ": 20,
    "LEARNING_RATE": 2e-4,
    "WEIGHT_DECAY": 1e-5,
    "W1": 0.5,
    "W2": 0.3,
    "K": 100,
    "ALPHA": 50,
    "AGENT_STRINGS": [
        "tight_aggressive",
        "heuristic_hands",
        "heuristic_hands",
        "loose_passive",
        "tight_aggressive",
        "random",
        "loose_passive",
        "small_ball",
        "tight_aggressive",
    ],
    "LOG_DIR": "results/Poker/logs",
}


def run_stability_benchmark(config_overrides: dict[str, object] | None = None) -> dict[str, object]:
    config = STABILITY_BENCHMARK_DEFAULTS.copy()
    if config_overrides is not None:
        config.update(config_overrides)

    device = load_device()
    
    # Setup logger
    log_dir = Path(config["LOG_DIR"])
    logger = TrainingLogger(str(log_dir))
    logger.log(f"Starting stability benchmark run #{logger.run_number}")
    logger.log("Configuration:", {
        "N_GAMES": config["N_GAMES"],
        "EPISODES": config["EPISODES"],
        "LEARNING_RATE": config["LEARNING_RATE"],
        "GAMMA": config["GAMMA"]
    })

    agents, agent_types = load_gpu_agents(
        device,
        config["NUM_PLAYERS"],
        config["AGENT_STRINGS"],
        config["STARTING_BBS"],
        config["POKER_ACTION_SPACE_N"],
    )
    
    # Median exploration vs exploitation setup
    q_net = PokerQNetwork(
        weights_path="",
        device=device,
        gamma=config["GAMMA"],
        update_freq=config["UPDATE_FREQ"],
        state_dim=config["STATE_SPACE"],
        action_dim=config["ACTION_SPACE"],
        learning_rate=config["LEARNING_RATE"],
        weight_decay=config["WEIGHT_DECAY"],
        epsilon=0.5,
        epsilon_decay=0.95,
        epsilon_end=0.05
    ).to(device)

    agents.insert(0, q_net)
    agent_types.insert(0, PokerAgentType.QLEARNING)
    
    env = gym.make(
        "Pulse-Poker-GPU-v1",
        device=device,
        agents=agents,
        n_players=config["NUM_PLAYERS"] + 1,
        n_games=config["N_GAMES"],
        starting_bbs=config["STARTING_BBS"],
        w1=config["W1"],
        w2=config["W2"],
        K=config["K"],
        alpha=config["ALPHA"]
    )

    actions = torch.zeros(config["N_GAMES"], dtype=torch.long, device=device)
    
    epoch_rewards = []
    epoch_q_means = []
    epoch_q_mins = []
    epoch_q_maxs = []
    epoch_td_errors = []
    epoch_clip_rates = []

    start_time = time.time()

    for episode in range(config["EPISODES"]):
        rotated_agents, rotated_types, q_seat, rotations = get_rotated_agents(
            agents, agent_types, episode_idx=episode
        )

        state, info = env.reset(options={
            'rotation': rotations,                    
            'active_players': True,
            'q_agent_seat': q_seat   
        })

        terminated = torch.zeros(config["N_GAMES"], dtype=torch.bool, device=device)
        termination_threshold = torch.tensor(0.8, device=device) 
        idx = 0
        
        episode_reward_tensor = torch.tensor(0.0, device=device) 
        step_metrics = []

        while True:
            actions.fill_(0)
            q_mask = (info['seat_idx'] == q_seat)
            build_actions(state, actions, info['seat_idx'], rotated_agents, rotated_types, device)
            
            state_snapshot = state.clone()
            next_state, rewards, dones, truncated, info = env.step(actions)
            
            terminated_before = terminated.clone() 
            terminated |= dones
            active_games = q_mask & ~terminated_before 
            
            # Perform training step
            train_metrics = run_stability_measured_q_learning_step(
                q_network=q_net,
                states=state_snapshot[active_games],
                actions=actions[active_games],
                rewards=rewards[active_games],
                next_states=next_state[active_games],
                dones=dones[active_games],
            )

            if train_metrics is not None:
                step_metrics.append(train_metrics)

            episode_reward_tensor += rewards[active_games].sum()
            state = next_state
            
            if idx % 5 == 0:
                if terminated.float().mean() > termination_threshold:
                    break
            idx += 1

        episode_summary = summarize_episode_stability_metrics(
            episode_reward=episode_reward_tensor.item(),
            step_metrics=step_metrics,
        )
        epoch_rewards.append(episode_summary["reward"])
        epoch_q_means.append(episode_summary["q_mean"])
        epoch_q_mins.append(episode_summary["q_min"])
        epoch_q_maxs.append(episode_summary["q_max"])
        epoch_td_errors.append(episode_summary["td_error"])
        epoch_clip_rates.append(episode_summary["clip_rate"])

        logger.log(f"Episode {episode + 1}/{config['EPISODES']} completed", episode_summary)
        
        if (episode + 1) % 5 == 0:
            print(
                f"Episode {episode + 1:2d}/{config['EPISODES']} | "
                f"Reward: {episode_summary['reward']:8.2f} | "
                f"TD Error: {episode_summary['td_error']:6.4f} | "
                f"Clip Rate: {episode_summary['clip_rate']:4.2f}"
            )

    elapsed = time.time() - start_time

    final_metrics = calculate_final_stability_metrics(
        epoch_rewards=epoch_rewards,
        epoch_q_means=epoch_q_means,
        epoch_q_mins=epoch_q_mins,
        epoch_q_maxs=epoch_q_maxs,
        epoch_td_errors=epoch_td_errors,
        epoch_clip_rates=epoch_clip_rates,
        elapsed_seconds=elapsed,
    )

    logger.log("Training Stability Benchmark Completed", final_metrics)
    
    print("\n" + "="*50)
    print("FINAL STABILITY METRICS:")
    print("="*50)
    print(f"Reward Std Dev (Stability): {final_metrics['reward_std']:.2f}")
    print(f"TD Error Trend (slope):     {final_metrics['td_error_trend']:.6f} (negative is better)")
    print(f"Average Gradient Clip Rate: {final_metrics['average_clip_rate']:.4f}")
    print(f"Q-Value Bounds:             [{final_metrics['q_bounds']['global_min']:.2f}, {final_metrics['q_bounds']['global_max']:.2f}]")
    print(f"Mean Q-Value:               {final_metrics['q_bounds']['mean_q']:.4f}")
    print(f"Total Run Time:             {elapsed:.2f}s")
    print("="*50)

    return final_metrics

if __name__ == "__main__":
    run_stability_benchmark()
