"""
DO NOT EDIT THIS FILE.

This file is a grading criteria artifact that measures the training stability
of the Poker GPU environment. It tracks reward stability, TD error trends,
Q-value bounds, and gradient clipping rates to ensure our agent is learning 
steadily over time.
"""

import gymnasium as gym
import torch
import time
import numpy as np
from pathlib import Path
from utils.torch import load_device
from environments.Poker.Player import PokerQNetwork
from environments.Poker.utils import PokerAgentType, build_actions, get_rotated_agents, load_gpu_agents
from utils.logging.logger import TrainingLogger

def run_stability_benchmark():
    # Hardcoded configuration for stability testing
    NUM_PLAYERS = 9
    N_GAMES = 100000 
    EPISODES = 50
    STARTING_BBS = 100
    POKER_ACTION_SPACE_N = 13
    STATE_SPACE = 40
    ACTION_SPACE = 13
    GAMMA = 0.95
    UPDATE_FREQ = 20
    LEARNING_RATE = 2e-4
    WEIGHT_DECAY = 1e-5
    
    # Environment specific weights
    W1 = 0.5
    W2 = 0.3
    K = 100
    ALPHA = 50

    AGENT_STRINGS = [
        "tight_aggressive", "heuristic_hands", "heuristic_hands", 
        "loose_passive", "tight_aggressive", "random", 
        "loose_passive", "small_ball", "tight_aggressive"
    ]

    device = load_device()
    
    # Setup logger
    log_dir = Path("results/Poker/logs")
    logger = TrainingLogger(str(log_dir))
    logger.log(f"Starting stability benchmark run #{logger.run_number}")
    logger.log("Configuration:", {
        "N_GAMES": N_GAMES,
        "EPISODES": EPISODES,
        "LEARNING_RATE": LEARNING_RATE,
        "GAMMA": GAMMA
    })

    agents, agent_types = load_gpu_agents(
        device, NUM_PLAYERS, AGENT_STRINGS, STARTING_BBS, POKER_ACTION_SPACE_N
    )
    
    # Median exploration vs exploitation setup
    q_net = PokerQNetwork(
        weights_path="", 
        device=device, 
        gamma=GAMMA, 
        update_freq=UPDATE_FREQ, 
        state_dim=STATE_SPACE, 
        action_dim=ACTION_SPACE,
        learning_rate=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY,
        epsilon=0.5,
        epsilon_decay=0.95,
        epsilon_end=0.05
    ).to(device)

    agents.insert(0, q_net)
    agent_types.insert(0, PokerAgentType.QLEARNING)
    
    env = gym.make(
        "Pulse-Poker-GPU-v1",
        device=device,
        agents=agents, 
        n_players=NUM_PLAYERS + 1,
        n_games=N_GAMES, 
        starting_bbs=STARTING_BBS, 
        w1=W1,
        w2=W2,
        K=K,
        alpha=ALPHA
    )

    actions = torch.zeros(N_GAMES, dtype=torch.long, device=device)
    
    epoch_rewards = []
    epoch_q_means = []
    epoch_q_mins = []
    epoch_q_maxs = []
    epoch_td_errors = []
    epoch_clip_rates = []

    start_time = time.time()

    for episode in range(EPISODES):
        rotated_agents, rotated_types, q_seat, rotations = get_rotated_agents(
            agents, agent_types, episode_idx=episode
        )

        state, info = env.reset(options={
            'rotation': rotations,                    
            'active_players': True,
            'q_agent_seat': q_seat   
        })

        terminated = torch.zeros(N_GAMES, dtype=torch.bool, device=device)
        termination_threshold = torch.tensor(0.8, device=device) 
        idx = 0
        
        episode_reward_tensor = torch.tensor(0.0, device=device) 
        
        step_q_means = []
        step_q_mins = []
        step_q_maxs = []
        step_td_errors = []
        step_clip_rates = []

        while True:
            actions.fill_(0)
            q_mask = (info['seat_idx'] == q_seat)
            build_actions(state, actions, info['seat_idx'], rotated_agents, rotated_types, device)
            
            state_snapshot = state.clone()
            next_state, rewards, dones, truncated, info = env.step(actions)
            
            terminated_before = terminated.clone() 
            terminated |= dones
            active_games = q_mask & ~terminated_before 
            
            # Perform training step
            train_metrics = agents[agent_types.index(PokerAgentType.QLEARNING)].train_step(
                states=state_snapshot[active_games],
                actions=actions[active_games],
                rewards=rewards[active_games],
                next_states=next_state[active_games],
                dones=dones[active_games]
            )

            if train_metrics is not None and isinstance(train_metrics, dict):
                step_q_means.append(train_metrics['q_mean'])
                step_q_mins.append(train_metrics['q_min'])
                step_q_maxs.append(train_metrics['q_max'])
                step_td_errors.append(train_metrics['td_error'])
                step_clip_rates.append(train_metrics['clip_rate'])

            episode_reward_tensor += rewards[active_games].sum()
            state = next_state
            
            if idx % 5 == 0:
                if terminated.float().mean() > termination_threshold:
                    break
            idx += 1

        ep_reward = episode_reward_tensor.item()
        epoch_rewards.append(ep_reward)
        
        ep_q_mean = np.mean(step_q_means) if step_q_means else 0.0
        ep_q_min = np.min(step_q_mins) if step_q_mins else 0.0
        ep_q_max = np.max(step_q_maxs) if step_q_maxs else 0.0
        ep_td_error = np.mean(step_td_errors) if step_td_errors else 0.0
        ep_clip_rate = np.mean(step_clip_rates) if step_clip_rates else 0.0

        epoch_q_means.append(ep_q_mean)
        epoch_q_mins.append(ep_q_min)
        epoch_q_maxs.append(ep_q_max)
        epoch_td_errors.append(ep_td_error)
        epoch_clip_rates.append(ep_clip_rate)

        logger.log(f"Episode {episode + 1}/{EPISODES} completed", {
            "reward": ep_reward,
            "q_mean": ep_q_mean,
            "q_min": ep_q_min,
            "q_max": ep_q_max,
            "td_error": ep_td_error,
            "clip_rate": ep_clip_rate
        })
        
        if (episode + 1) % 5 == 0:
            print(f"Episode {episode + 1:2d}/{EPISODES} | Reward: {ep_reward:8.2f} | TD Error: {ep_td_error:6.4f} | Clip Rate: {ep_clip_rate:4.2f}")

    elapsed = time.time() - start_time

    # Calculate final stability metrics
    reward_std = np.std(epoch_rewards)
    # Fit a line to TD errors to find the trend (negative slope means TD error is decreasing)
    td_error_trend = np.polyfit(np.arange(EPISODES), epoch_td_errors, 1)[0] if len(epoch_td_errors) > 1 else 0.0
    
    final_metrics = {
        "reward_std": reward_std,
        "mean_reward": np.mean(epoch_rewards),
        "q_bounds": {
            "global_min": np.min(epoch_q_mins),
            "global_max": np.max(epoch_q_maxs),
            "mean_q": np.mean(epoch_q_means)
        },
        "td_error_trend": td_error_trend,
        "average_clip_rate": np.mean(epoch_clip_rates),
        "total_time_seconds": elapsed
    }

    logger.log("Training Stability Benchmark Completed", final_metrics)
    
    print("\n" + "="*50)
    print("FINAL STABILITY METRICS:")
    print("="*50)
    print(f"Reward Std Dev (Stability): {final_metrics['reward_std']:.2f}")
    print(f"TD Error Trend (slope):     {final_metrics['td_error_trend']:.6f} (negative is better)")
    print(f"Average Gradient Clip Rate: {final_metrics['average_clip_rate']:.4f}")
    print(f"Q-Value Bounds:             [{final_metrics['q_bounds']['global_min']:.2f}, {final_metrics['q_bounds']['global_max']:.2f}]")
    print(f"Mean Q-Value:               {final_metrics['q_bounds']['mean_q']:.4f}")
    print(f"Total Run Time:             {elapsed:.2f}s")
    print("="*50)

    return final_metrics

if __name__ == "__main__":
    run_stability_benchmark()
