"""
DO NOT EDIT THIS FILE.

This file is a grading criteria artifact that measures the training performance
of the Poker GPU environment. It tracks cumulative reward, reward improvement,
field BB/100, paired field BB/100, LCB95 BB/100, seat-balanced BB/100,
worst-slice BB/100, street-specific hand wins, and position-based win rates
for the Q-learning agent.
"""

from __future__ import annotations

import time
from pathlib import Path

import gymnasium as gym
import torch

from environments.Poker.Player import PokerQNetwork
from environments.Poker.utils import PokerAgentType, build_actions, get_rotated_agents, load_gpu_agents
from utils.logging.logger import TrainingLogger
from utils.performance import (
    build_opponent_mix_description,
    build_prefixed_deck_batch,
    calculate_final_performance_metrics,
    calculate_q_seat_positions,
    format_nested_metric_values,
    format_scalar_metric_map,
    summarize_episode_performance_metrics,
)
from utils.torch import load_device


PERFORMANCE_BENCHMARK_DEFAULTS = {
    "NUM_PLAYERS": 9,
    "N_GAMES": 100000,
    "EPISODES": 50,
    "STARTING_BBS": 100,
    "POKER_ACTION_SPACE_N": 13,
    "STATE_SPACE": 40,
    "ACTION_SPACE": 13,
    "GAMMA": 0.95,
    "UPDATE_FREQ": 20,
    "LEARNING_RATE": 2e-4,
    "WEIGHT_DECAY": 1e-5,
    "W1": 0.5,
    "W2": 0.3,
    "K": 100,
    "ALPHA": 50,
    "ROLLING_WINDOW_SIZE": 100,
    "USE_PREFIXED_DECKS": True,
    "DECK_SEED": 20260401,
    "AGENT_STRINGS": [
        "tight_aggressive",
        "heuristic_hands",
        "heuristic_hands",
        "loose_passive",
        "tight_aggressive",
        "random",
        "loose_passive",
        "small_ball",
        "tight_aggressive",
    ],
    "LOG_DIR": "results/Poker/logs",
}


def run_performance_benchmark(config_overrides: dict[str, object] | None = None) -> dict[str, object]:
    """Run the fixed poker GPU performance benchmark with tensor-native aggregation."""
    config = PERFORMANCE_BENCHMARK_DEFAULTS.copy()
    if config_overrides is not None:
        config.update(config_overrides)

    device = load_device()

    log_dir = Path(config["LOG_DIR"])
    logger = TrainingLogger(str(log_dir))
    logger.log(f"Starting performance benchmark run #{logger.run_number}")
    logger.log(
        "Configuration:",
        {
            "N_GAMES": config["N_GAMES"],
            "EPISODES": config["EPISODES"],
            "LEARNING_RATE": config["LEARNING_RATE"],
            "GAMMA": config["GAMMA"],
            "ROLLING_WINDOW_SIZE": config["ROLLING_WINDOW_SIZE"],
            "USE_PREFIXED_DECKS": config["USE_PREFIXED_DECKS"],
            "DECK_SEED": config["DECK_SEED"],
        },
    )

    agents, agent_types = load_gpu_agents(
        device,
        config["NUM_PLAYERS"],
        config["AGENT_STRINGS"],
        config["STARTING_BBS"],
        config["POKER_ACTION_SPACE_N"],
    )

    q_net = PokerQNetwork(
        weights_path="",
        device=device,
        gamma=config["GAMMA"],
        update_freq=config["UPDATE_FREQ"],
        state_dim=config["STATE_SPACE"],
        action_dim=config["ACTION_SPACE"],
        learning_rate=config["LEARNING_RATE"],
        weight_decay=config["WEIGHT_DECAY"],
        epsilon=0.5,
        epsilon_decay=0.95,
        epsilon_end=0.05,
    ).to(device)

    agents.insert(0, q_net)
    agent_types.insert(0, PokerAgentType.QLEARNING)

    env = gym.make(
        "Pulse-Poker-GPU-v1",
        device=device,
        agents=agents,
        n_players=config["NUM_PLAYERS"] + 1,
        n_games=config["N_GAMES"],
        starting_bbs=config["STARTING_BBS"],
        w1=config["W1"],
        w2=config["W2"],
        K=config["K"],
        alpha=config["ALPHA"],
    )

    actions = torch.zeros(config["N_GAMES"], dtype=torch.long, device=device)
    epoch_rewards: list[torch.Tensor] = []
    hand_bb_deltas: list[torch.Tensor] = []
    hand_terminal_stages: list[torch.Tensor] = []
    hand_positions: list[torch.Tensor] = []
    hand_player_counts: list[torch.Tensor] = []
    hand_opponent_mix_ids: list[torch.Tensor] = []
    cumulative_reward = torch.zeros((), device=device)
    opponent_mix_descriptions = {
        "mix_0": build_opponent_mix_description(list(config["AGENT_STRINGS"]))
    }

    start_time = time.time()

    for episode in range(config["EPISODES"]):
        rotated_agents, rotated_types, q_seat, rotations = get_rotated_agents(
            agents, agent_types, episode_idx=episode
        )
        prefixed_decks = None
        if config["USE_PREFIXED_DECKS"]:
            prefixed_decks = build_prefixed_deck_batch(
                n_games=config["N_GAMES"],
                seed=int(config["DECK_SEED"]) + episode,
                device=device,
            )

        state, info = env.reset(
            options={
                "rotation": rotations,
                "active_players": True,
                "q_agent_seat": q_seat,
                "prefixed_decks": prefixed_decks,
            }
        )

        initial_q_stacks = info["stacks"][:, q_seat].clone()
        q_positions = calculate_q_seat_positions(env.button, q_seat=q_seat, active_players=env.active_players)
        hand_player_count = torch.full((config["N_GAMES"],), env.active_players, dtype=torch.int64, device=device)
        hand_opponent_mix_id = torch.zeros(config["N_GAMES"], dtype=torch.int64, device=device)

        terminated = torch.zeros(config["N_GAMES"], dtype=torch.bool, device=device)
        termination_threshold = torch.tensor(0.8, device=device)
        idx = 0

        episode_reward_tensor = torch.zeros((), device=device)
        episode_hand_deltas: list[torch.Tensor] = []

        while True:
            actions.fill_(0)
            q_mask = info["seat_idx"] == q_seat
            build_actions(state, actions, info["seat_idx"], rotated_agents, rotated_types, device)

            state_snapshot = state.clone()
            next_state, rewards, dones, truncated, info = env.step(actions)

            terminated_before = terminated.clone()
            terminated |= dones
            active_games = q_mask & ~terminated_before
            newly_done = dones & ~terminated_before

            q_net.train_step(
                states=state_snapshot[active_games],
                actions=actions[active_games],
                rewards=rewards[active_games],
                next_states=next_state[active_games],
                dones=dones[active_games],
            )

            if newly_done.any():
                final_q_stacks = info["stacks"][newly_done, q_seat].to(dtype=torch.float32)
                completed_hand_deltas = final_q_stacks - initial_q_stacks[newly_done].to(dtype=torch.float32)
                hand_bb_deltas.append(completed_hand_deltas.detach())
                hand_terminal_stages.append(env.stages[newly_done].to(dtype=torch.int64).detach().clone())
                hand_positions.append(q_positions[newly_done].detach().clone())
                hand_player_counts.append(hand_player_count[newly_done].detach().clone())
                hand_opponent_mix_ids.append(hand_opponent_mix_id[newly_done].detach().clone())
                episode_hand_deltas.append(completed_hand_deltas.detach())

            episode_reward_tensor += rewards[active_games].sum()
            state = next_state

            if idx % 5 == 0:
                if terminated.float().mean() > termination_threshold:
                    break
            idx += 1

        cumulative_reward += episode_reward_tensor
        episode_summary = summarize_episode_performance_metrics(
            episode_reward=episode_reward_tensor,
            cumulative_reward=cumulative_reward,
            hand_bb_deltas=episode_hand_deltas,
        )
        epoch_rewards.append(episode_summary["reward"])

        logger.log(f"Episode {episode + 1}/{config['EPISODES']} completed", episode_summary)

        if (episode + 1) % 5 == 0:
            print(
                f"Episode {episode + 1:2d}/{config['EPISODES']} | "
                f"Reward: {episode_summary['reward'].item():8.2f} | "
                f"Cumulative Reward: {episode_summary['cumulative_reward'].item():8.2f} | "
                f"Mean BB Delta: {episode_summary['mean_bb_delta'].item():6.2f} | "
                f"Field BB/100: {episode_summary['field_bb_per_100'].item():7.2f}"
            )

    elapsed = time.time() - start_time

    final_metrics = calculate_final_performance_metrics(
        epoch_rewards=epoch_rewards,
        hand_bb_deltas=hand_bb_deltas,
        hand_terminal_stages=hand_terminal_stages,
        hand_positions=hand_positions,
        hand_player_counts=hand_player_counts,
        hand_opponent_mix_ids=hand_opponent_mix_ids,
        elapsed_seconds=elapsed,
        rolling_window_size=config["ROLLING_WINDOW_SIZE"],
        use_prefixed_decks=bool(config["USE_PREFIXED_DECKS"]),
        opponent_mix_descriptions=opponent_mix_descriptions,
    )
    final_metrics["paired_deck_seed"] = int(config["DECK_SEED"]) if config["USE_PREFIXED_DECKS"] else None

    logger.log("Training Performance Benchmark Completed", final_metrics)

    print("\n" + "=" * 50)
    print("FINAL PERFORMANCE METRICS:")
    print("=" * 50)
    print(f"Cumulative Reward:          {final_metrics['cumulative_reward'].item():.2f}")
    print(f"Reward Slope:               {final_metrics['reward_improvement']['slope'].item():.6f}")
    print(
        "Reward % Change:            "
        f"{final_metrics['reward_improvement']['first_to_last_percent_change'].item():.2f}%"
    )
    print(f"Field BB/100:               {final_metrics['field_bb_per_100'].item():.2f}")
    print(f"Paired Field BB/100:        {final_metrics['paired_field_bb_per_100'].item():.2f}")
    print(f"Paired Decks Enabled:       {final_metrics['paired_prefixed_decks_enabled']}")
    print(f"LCB95 BB/100:               {final_metrics['lcb95_bb_per_100'].item():.2f}")
    print(f"Seat-Balanced BB/100:       {final_metrics['seat_balanced_bb_per_100'].item():.2f}")
    print(f"Worst-Slice BB/100:         {final_metrics['worst_slice_bb_per_100'].item():.2f}")
    print(f"Total Big Blinds Won:       {final_metrics['total_bb_won'].item():.2f}")
    print(
        f"Rolling {final_metrics['rolling_bb_window']['window_size']}-Hand Avg BB:    "
        f"{final_metrics['rolling_bb_window']['last_average'].item():.2f}"
    )
    print(f"Overall Hand Win Rate:      {final_metrics['overall_hand_win_rate'].item():.4f}")
    print(f"Total Hands:                {final_metrics['total_hands'].item()}")
    print(f"Street Win %:               {format_scalar_metric_map(final_metrics['street_win_percentages'])}")
    print(f"Position Win %:             {format_scalar_metric_map(final_metrics['position_win_rates'])}")
    print(f"Slice BB/100:               {format_nested_metric_values(final_metrics['slice_bb_per_100'])}")
    print(f"Worst Slice Details:        {format_nested_metric_values(final_metrics['worst_slice_details'])}")
    print(f"Total Run Time:             {final_metrics['total_time_seconds'].item():.2f}s")
    print("=" * 50)

    return final_metrics


if __name__ == "__main__":
    run_performance_benchmark()
